(()=>{
'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fn=v=>new Intl.NumberFormat('vi-VN').format(Number(v)||0);
const skuKey=v=>String(v||'').trim().toLowerCase().replace(/[\s_-]+/g,'');
const itemSku=i=>String(i?.sku||i?.SKU||i?.mahang||i?.product_sku||i?.productSku||i?.item_sku||i?.itemSku||i?.variation_sku||i?.variationSku||'').trim();
function parseApiDate(v){const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?new Date(Number(m[1]),Number(m[2])-1,Number(m[3])):null}
function isSpecialLimitDate(d){if(!(d instanceof Date)||Number.isNaN(d.getTime()))return false;const day=d.getDate(),month=d.getMonth()+1;return day===1||day===10||day===15||day===20||day===25||day===month}
function rangeHasSpecialLimitDate(start,end){const a=parseApiDate(start),b=parseApiDate(end);if(!a||!b)return false;a.setHours(0,0,0,0);b.setHours(0,0,0,0);if(a>b)return false;const cur=new Date(a);for(let i=0;i<400&&cur<=b;i++,cur.setDate(cur.getDate()+1))if(isSpecialLimitDate(cur))return true;return false}
function patchPayloadLimit(){if(typeof window.payload!=='function'||window.payload.__specialLimitPatched)return;const original=window.payload;function patched(start,end,statuses,page,limit){const requested=Number(limit)||100;const next=rangeHasSpecialLimitDate(start,end)?Math.max(requested,400):requested;return original.call(this,start,end,statuses,page,next)}patched.__specialLimitPatched=true;window.payload=patched}
function patchReport(){if(typeof window.renderReport!=='function'||window.renderReport.__skuGrouped)return;const original=window.renderReport;function grouped(rows){const canonical=new Map();const out=(Array.isArray(rows)?rows:[]).map(r=>{if(!r||typeof r!=='object')return r;const copy={...r};let list=r.eoi_listproduct;try{list=typeof list==='string'?JSON.parse(list):list}catch(_){list=[]}if(list&&typeof list==='object'&&!Array.isArray(list))for(const k of['items','products','list'])if(Array.isArray(list[k])){list=list[k];break}if(Array.isArray(list)){copy.eoi_listproduct=list.map(it=>{if(!it||typeof it!=='object')return it;const x={...it},raw=itemSku(it),key=skuKey(raw);if(key){const shown=canonical.get(key)||raw;canonical.set(key,shown);x.sku=shown;x.mahang=shown;x.product_sku=shown}return x})}return copy});return original.call(this,out)}grouped.__skuGrouped=true;window.renderReport=grouped}
function css(){if($('skuFilterStyle'))return;const s=document.createElement('style');s.id='skuFilterStyle';s.textContent=`.sku-filter-btn{height:42px;width:42px;min-width:42px;padding:0;border:1px solid #2b4567;border-radius:10px;background:#13243a;color:#dceaff;font-size:19px;font-weight:800;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;flex:0 0 42px}.sku-filter-btn:hover,.sku-filter-btn.active{background:#1267d9;color:#fff;border-color:#4b8cff}.sku-modal-backdrop{position:fixed;inset:0;z-index:1000;background:rgba(3,9,18,.72);backdrop-filter:blur(5px);display:none;align-items:center;justify-content:center;padding:20px}.sku-modal-backdrop.open{display:flex}.sku-modal{width:min(1080px,100%);max-height:84vh;background:#0f1a2b;border:1px solid #29415f;border-radius:16px;overflow:hidden}.sku-modal-head{display:flex;justify-content:space-between;align-items:center;padding:17px 20px;border-bottom:1px solid #20334d}.sku-modal-title{font-size:18px;font-weight:800}.sku-modal-sub{font-size:11px;color:#8fa3c0;margin-top:4px}.sku-close{width:38px;height:38px;border:1px solid #304763;border-radius:10px;background:#132239;color:#fff;font-size:22px;cursor:pointer}.sku-modal-body{overflow:auto;max-height:65vh}.sku-table{width:100%;border-collapse:collapse}.sku-table th{background:#132239;color:#91a7c2}.sku-table th,.sku-table td{padding:10px 14px;border-bottom:1px solid #1a2c43;text-align:left}.sku-table th:nth-child(n+3),.sku-table td:nth-child(n+3){text-align:right}.sku-product{display:flex;align-items:center;gap:11px}.sku-product-img{width:52px;height:52px;border-radius:8px;object-fit:cover}.profit-rate-colored{font-weight:800}.kpi-value{margin-top:4px!important;padding-left:36px!important}@media(max-width:760px){.orders-head{display:flex!important;align-items:center!important;gap:8px!important}.orders-head .search{flex:1;min-width:0}.sku-modal-backdrop{padding:8px}.sku-modal{width:100%;max-height:100%}.sku-table thead{display:none}.sku-table,.sku-table tbody,.sku-table tr,.sku-table td{display:block;width:100%}.sku-table tr{padding:12px;border-bottom:1px solid #1a2c43}.sku-table td{border:0;padding:4px 0}.sku-table td:nth-child(3)::before{content:'Số lượng SKU: ';color:#7187a3}.sku-table td:nth-child(4)::before{content:'Số lượng đơn: ';color:#7187a3}}`;document.head.appendChild(s)}
function summary(){const rows=[...document.querySelectorAll('#ordersList .order-row:not(.head)')],m=new Map();for(const row of rows){const p=row.querySelector('.product-cell');if(!p)continue;const t=[...p.querySelectorAll('.muted')].map(x=>x.textContent.trim()),z=t.find(x=>/^SKU\s*:/i.test(x))||'',sku=z.replace(/^SKU\s*:\s*/i,'').trim();if(!sku||sku==='—')continue;const name=(p.querySelector('.name')?.textContent||'Sản phẩm').trim(),image=p.querySelector('img')?.src||'',qm=(t.find(x=>/×/.test(x))||'').match(/×\s*([\d.,]+)/),qty=qm?Number(qm[1].replace(/\./g,'').replace(',','.')):1,oid=(row.querySelectorAll('.cell')[4]?.textContent||'').trim(),key=skuKey(sku);let x=m.get(key);if(!x)x={sku,name,image,qty:0,orders:new Set()};x.qty+=Number.isFinite(qty)&&qty>0?qty:1;if(oid&&oid!=='—')x.orders.add(oid);m.set(key,x)}return{rows:[...m.values()].sort((a,b)=>b.qty-a.qty||b.orders.size-a.orders.size),count:rows.length}}
function renderSku(){const b=$('skuModalBody');if(!b)return;const r=summary();$('skuModalSub').textContent=`Từ ${fn(r.count)} đơn đang hiển thị`;$('skuModalFoot').textContent=`${fn(r.rows.length)} SKU`;b.innerHTML=r.rows.length?`<table class="sku-table"><thead><tr><th>Ảnh, Tên SP</th><th>Mã SKU</th><th>Số lượng SKU</th><th>Số lượng đơn</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td><div class="sku-product">${x.image?`<img class="sku-product-img" src="${esc(x.image)}">`:''}<div>${esc(x.name)}</div></div></td><td>${esc(x.sku)}</td><td>${fn(x.qty)}</td><td>${fn(x.orders.size)}</td></tr>`).join('')}</tbody></table>`:'<div style="padding:48px;text-align:center;color:#8fa3c0">Không tìm thấy SKU trong danh sách đơn hàng hiện tại.</div>'}
function install(){const h=document.querySelector('.orders-head');if(!h)return;if(!$('skuFilterBtn')){const b=document.createElement('button');b.type='button';b.id='skuFilterBtn';b.className='sku-filter-btn';b.title='Lọc SKU';b.textContent='▦';b.onclick=()=>{const m=$('skuModal');if(m){m.classList.add('open');renderSku()}};h.appendChild(b)}if(!$('skuModal')){const w=document.createElement('div');w.id='skuModal';w.className='sku-modal-backdrop';w.innerHTML='<div class="sku-modal"><div class="sku-modal-head"><div><div class="sku-modal-title">Lọc SKU</div><div class="sku-modal-sub" id="skuModalSub"></div></div><button type="button" class="sku-close" id="skuClose">×</button></div><div class="sku-modal-body" id="skuModalBody"></div><div style="padding:10px 16px;color:#7489a4;font-size:11px" id="skuModalFoot"></div></div>';document.body.appendChild(w);$('skuClose').onclick=()=>w.classList.remove('open');w.onclick=e=>{if(e.target===w)w.classList.remove('open')}}}
function paintRates(){for(const row of document.querySelectorAll('#ordersList .order-row:not(.head)'))for(const cell of row.querySelectorAll('.cell')){if(cell.dataset.ratePainted==='1')continue;const m=(cell.textContent||'').match(/(-?\d+(?:[.,]\d+)?)\s*%/);if(!m)continue;const v=Number(m[1].replace(',','.'));if(!Number.isFinite(v))continue;const c=v<11?'#ff4d67':v<14?'#ffb020':v<=16?'#3478f6':'#2ccf93';cell.innerHTML=cell.innerHTML.replace(m[0],`<span class="profit-rate-colored" style="color:${c}">${m[0]}</span>`);cell.dataset.ratePainted='1'}}
css();patchPayloadLimit();patchReport();const ob=new MutationObserver(()=>{install();paintRates();patchPayloadLimit();patchReport()});ob.observe(document.documentElement,{childList:true,subtree:true});install();paintRates();setInterval(()=>{patchPayloadLimit();patchReport()},250);
})();