(()=>{
'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fn=v=>new Intl.NumberFormat('vi-VN').format(Number(v)||0);
function css(){if($('skuFilterStyle'))return;const s=document.createElement('style');s.id='skuFilterStyle';s.textContent=`
.sku-filter-btn{height:42px;width:42px;min-width:42px;padding:0;border:1px solid #2b4567;border-radius:10px;background:#13243a;color:#dceaff;font-size:19px;font-weight:800;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;flex:0 0 42px}.sku-filter-btn:hover,.sku-filter-btn.active{background:#1267d9;color:#fff;border-color:#4b8cff}
.sku-modal-backdrop{position:fixed;inset:0;z-index:1000;background:rgba(3,9,18,.72);backdrop-filter:blur(5px);display:none;align-items:center;justify-content:center;padding:20px}.sku-modal-backdrop.open{display:flex}.sku-modal{width:min(1080px,100%);max-height:84vh;background:#0f1a2b;border:1px solid #29415f;border-radius:16px;box-shadow:0 25px 90px rgba(0,0,0,.5);overflow:hidden;display:flex;flex-direction:column}.sku-modal-head{display:flex;justify-content:space-between;align-items:center;padding:17px 20px;border-bottom:1px solid #20334d}.sku-modal-title{font-size:18px;font-weight:800}.sku-modal-sub{font-size:11px;color:#8fa3c0;margin-top:4px}.sku-close{width:38px;height:38px;border:1px solid #304763;border-radius:10px;background:#132239;color:#fff;font-size:22px;cursor:pointer}.sku-modal-body{overflow:auto}.sku-table{width:100%;border-collapse:collapse}.sku-table th{position:sticky;top:0;background:#132239;color:#91a7c2;font-size:11px;text-align:left;padding:11px 14px;border-bottom:1px solid #29405c}.sku-table td{padding:10px 14px;border-bottom:1px solid #1a2c43;font-size:13px}.sku-table th:nth-child(n+3),.sku-table td:nth-child(n+3){text-align:right}.sku-product{display:flex;align-items:center;gap:11px;min-width:0}.sku-product-img{width:52px;height:52px;border-radius:8px;object-fit:cover;background:#26364d;flex:0 0 auto}.sku-product-name{font-weight:750;line-height:1.3}.sku-number{font-size:15px;font-weight:800}.sku-empty,.sku-loading{padding:48px;text-align:center;color:#8fa3c0}.sku-modal-foot{padding:11px 16px;color:#7489a4;font-size:11px;border-top:1px solid #1a2c43}
@media(max-width:760px){.orders-head{display:flex!important;align-items:center!important;gap:8px!important;width:100%!important}.orders-head .search{flex:1 1 auto!important;min-width:0!important;width:auto!important}.orders-head .sku-filter-btn{display:inline-flex!important;flex:0 0 42px!important;width:42px!important;min-width:42px!important}.sku-modal-backdrop{padding:8px;align-items:stretch}.sku-modal{width:100%;max-height:100%;border-radius:14px}.sku-modal-head{padding:13px 14px}.sku-modal-body{overflow-x:hidden;overflow-y:auto}.sku-table,.sku-table tbody{display:block;width:100%;min-width:0}.sku-table thead{display:none}.sku-table tr{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:0 12px;padding:12px;border-bottom:1px solid #1a2c43;min-width:0}.sku-table td{display:block;border:0;padding:4px 0;min-width:0;overflow-wrap:anywhere}.sku-table td:nth-child(1){grid-column:1/-1;grid-row:1}.sku-table td:nth-child(2){grid-column:1/-1;grid-row:2;color:#91a7c2;font-size:12px;padding-top:0}.sku-table td:nth-child(3){grid-column:1;grid-row:3;text-align:left;font-size:12px}.sku-table td:nth-child(4){grid-column:2;grid-row:3;text-align:right;font-size:12px}.sku-table td:nth-child(3)::before{content:'Số lượng SKU: ';color:#7187a3;font-weight:600}.sku-table td:nth-child(4)::before{content:'Số lượng đơn: ';color:#7187a3;font-weight:600}.sku-product{width:100%;gap:10px}.sku-product-img{width:56px;height:56px}.sku-product-name{font-size:14px;white-space:normal;overflow-wrap:anywhere}}
`;document.head.appendChild(s)}
function summary(){const rows=[...document.querySelectorAll('#ordersList .order-row:not(.head)')],m=new Map();for(const row of rows){const p=row.querySelector('.product-cell');if(!p)continue;const t=[...p.querySelectorAll('.muted')].map(x=>x.textContent.trim()),z=t.find(x=>/^SKU\s*:/i.test(x))||'',sku=z.replace(/^SKU\s*:\s*/i,'').trim();if(!sku||sku==='—')continue;const name=(p.querySelector('.name')?.textContent||'Sản phẩm').trim(),image=p.querySelector('img')?.src||'',qm=(t.find(x=>/×/.test(x))||'').match(/×\s*([\d.,]+)/),qty=qm?Number(qm[1].replace(/\./g,'').replace(',','.')):1,oid=(row.querySelectorAll('.cell')[4]?.textContent||'').trim(),key=sku.toLowerCase();let x=m.get(key);if(!x)x={sku,name,image,qty:0,orders:new Set()};x.qty+=Number.isFinite(qty)&&qty>0?qty:1;if(oid&&oid!=='—')x.orders.add(oid);if(!x.image)x.image=image;m.set(key,x)}return{rows:[...m.values()].sort((a,b)=>b.qty-a.qty||b.orders.size-a.orders.size),count:rows.length}}
function render(){const b=$('skuModalBody');if(!b)return;b.innerHTML='<div class="sku-loading">Đang tổng hợp SKU...</div>';const r=summary();$('skuModalSub').textContent=`Từ ${fn(r.count)} đơn đang hiển thị`;$('skuModalFoot').textContent=`${fn(r.rows.length)} SKU`;if(!r.rows.length){b.innerHTML='<div class="sku-empty">Không tìm thấy SKU trong danh sách đơn hàng hiện tại.</div>';return}b.innerHTML=`<table class="sku-table"><thead><tr><th>Ảnh, Tên SP</th><th>Mã SKU</th><th>Số lượng SKU</th><th>Số lượng đơn</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td><div class="sku-product">${x.image?`<img class="sku-product-img" src="${esc(x.image)}">`:''}<div class="sku-product-name">${esc(x.name)}</div></div></td><td>${esc(x.sku)}</td><td><span class="sku-number">${fn(x.qty)}</span></td><td><span class="sku-number">${fn(x.orders.size)}</span></td></tr>`).join('')}</tbody></table>`}
function open(){const m=$('skuModal');if(m){m.classList.add('open');$('skuFilterBtn')?.classList.add('active');render()}}function close(){const m=$('skuModal');if(m)m.classList.remove('open');$('skuFilterBtn')?.classList.remove('active')}
function install(){const h=document.querySelector('.orders-head');if(!h)return;if(!$('skuFilterBtn')){const b=document.createElement('button');b.type='button';b.id='skuFilterBtn';b.className='sku-filter-btn';b.title='Lọc SKU';b.setAttribute('aria-label','Lọc SKU');b.textContent='▦';b.addEventListener('click',open);h.appendChild(b)}if(!$('skuModal')){const w=document.createElement('div');w.id='skuModal';w.className='sku-modal-backdrop';w.innerHTML='<div class="sku-modal" role="dialog" aria-modal="true"><div class="sku-modal-head"><div><div class="sku-modal-title">Lọc SKU</div><div class="sku-modal-sub" id="skuModalSub"></div></div><button type="button" class="sku-close" id="skuClose">×</button></div><div class="sku-modal-body" id="skuModalBody"></div><div class="sku-modal-foot" id="skuModalFoot"></div></div>';document.body.appendChild(w);$('skuClose').addEventListener('click',close);w.addEventListener('click',e=>{if(e.target===w)close()})}}
function rateColor(v){if(v<11)return'#ff4d67';if(v<14)return'#ffb020';if(v<=16)return'#3478f6';return'#2ccf93'}
function paintRates(){document.querySelectorAll('#ordersList .order-row:not(.head) .cell').forEach(cell=>{const text=(cell.textContent||'').trim();const m=text.match(/^(-?\d+(?:[.,]\d+)?)\s*%$/);if(!m)return;const value=Number(m[1].replace(',','.'));if(!Number.isFinite(value))return;cell.style.color=rateColor(value);cell.style.fontWeight='800'})}
css();const observer=new MutationObserver(()=>{install();paintRates()});observer.observe(document.body,{childList:true,subtree:true});install();paintRates();document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
})();