(()=>{'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fn=v=>new Intl.NumberFormat('vi-VN').format(Number(v)||0);
const skuKey=v=>String(v||'').trim().toLowerCase().replace(/[\s_-]+/g,'');
const BRAND='data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAQCdASoAAACAAUAmJaQAA3AA/v3Ff8uUAAA=';

/* Desktop KPI layout kept clean. */
const desktopStyle=document.createElement('style');desktopStyle.id='kpiDesktopLayoutOverride';
desktopStyle.textContent=`@media(min-width:761px){.cards .kpi{min-height:66px!important;height:66px!important;padding:8px 20px!important;display:grid!important;grid-template-columns:28px max-content!important;grid-template-rows:auto auto!important;column-gap:18px!important;row-gap:3px!important;justify-content:start!important;align-content:center!important}.cards .kpi-head{display:contents!important}.cards .kpi-icon{grid-column:1!important;grid-row:1 / span 2!important;width:28px!important;height:28px!important;align-self:center!important}.cards .kpi-title{grid-column:2!important;grid-row:1!important;margin:0!important;padding:0!important;white-space:nowrap!important}.cards .kpi-value{grid-column:2!important;grid-row:2!important;margin:0!important;padding:0!important;transform:none!important;justify-self:start!important;font-size:24px!important;line-height:1.05!important;white-space:nowrap!important}}.abit-product-list{width:100%;display:flex;flex-direction:column;gap:10px}.abit-product-item{display:flex;align-items:center;gap:10px;min-width:0}.abit-product-info{min-width:0;flex:1}.order-row>.product-cell{align-items:flex-start!important}.abit-brand-logo{width:34px;height:34px;border-radius:9px;object-fit:cover;vertical-align:middle;box-shadow:0 3px 14px rgba(52,120,246,.25)}.login-card .logo{background:transparent!important;padding:0!important;overflow:hidden}.login-card .logo img{width:100%;height:100%;object-fit:cover}.sidebar .brand{display:flex!important;align-items:center;gap:9px;padding:8px 10px 20px!important;font-weight:800}.sidebar .brand img{width:32px;height:32px;border-radius:9px;object-fit:cover}`;
document.head.appendChild(desktopStyle);

function parseMahang(raw){return String(raw??'').split(',').map(x=>x.trim()).filter(Boolean).map(part=>{const m=part.match(/^\(\s*(\d+)\s*\)\s*(.+?)\s*$/);return{sku:(m?m[2]:part).trim(),qty:m?Math.max(1,Number(m[1])||1):1}}).filter(x=>x.sku)}
function rawItems(r){let x=r?.eoi_listproduct;if(!x)return[];try{x=typeof x==='string'?JSON.parse(x):x}catch{return[]}if(x&&typeof x==='object'&&!Array.isArray(x))for(const k of['items','products','list'])if(Array.isArray(x[k])){x=x[k];break}return Array.isArray(x)?x.filter(Boolean):[]}
function orderProducts(r){const base=rawItems(r),codes=parseMahang(r?.mahang??r?.ma_hang??r?.maHang??r?.sku_list??r?.skuList);if(!codes.length)return base.map((x,i)=>({...x,__qty:Number(x?.quantity??x?.qty??1)||1,__index:i}));const out=[];for(let i=0;i<codes.length;i++){const src={...(base[i]||base[0]||{})};const code=codes[i];src.sku=code.sku;src.SKU=code.sku;src.mahang=code.sku;src.product_sku=code.sku;src.productSku=code.sku;src.quantity=code.qty;src.qty=code.qty;src.amount=code.qty;src.count=code.qty;src.__qty=code.qty;src.__index=i;out.push(src)}return out}
function itemSku(i,r){return String(i?.mahang??i?.sku??i?.SKU??i?.product_sku??i?.productSku??r?.mahang??'').trim()}
function itemQty(i){const n=Number(i?.__qty??i?.quantity??i?.qty??i?.amount??i?.count??1);return Number.isFinite(n)&&n>0?n:1}
function itemName(i){return String(i?.item_name??i?.itemName??i?.product_name??i?.productName??i?.name??'Sản phẩm').trim()||'Sản phẩm'}
function itemImage(i){for(const k of['image_url','imageurl','imageUrl','url','image','thumbnail','thumbnail_url','thumbnailUrl','src','original_image','originalImage','picture','pic','main_image','mainImage']){const v=i?.[k];if(typeof v==='string'&&/^https?:\/\//i.test(v))return v.trim();if(v&&typeof v==='object')for(const sk of['url','imageUrl','image_url','src','original']){const q=v[sk];if(typeof q==='string'&&/^https?:\/\//i.test(q))return q.trim()}}return''}

/* Important: transform the actual argument before original report code reads eoi_listproduct. */
function patchReport(){if(typeof renderReport!=='function'||renderReport.__abitMahang)return;const original=renderReport;function patched(rows,...rest){const transformed=(Array.isArray(rows)?rows:[]).map(r=>{const products=orderProducts(r);if(!products.length)return r;return {...r,eoi_listproduct:products}});return original.call(this,transformed,...rest)}patched.__abitMahang=true;globalThis.renderReport=patched}
function visibleRecords(){try{const data=(typeof state!=='undefined'&&Array.isArray(state.orderRows))?state.orderRows:[];const q=String($('#search')?.value||'').toLowerCase().trim();if(!q)return data;return data.filter(r=>{const text=[r.eoi_order_id,r.order_id,r.orderId,r.tracking_no,r.trackingNo,r.subject,r.store_name,r.brand,r.createdtime,...orderProducts(r).flatMap(i=>[itemName(i),itemSku(i,r),i.product_sku,i.mahang])].filter(Boolean).join(' ').toLowerCase();return text.includes(q)})}catch{return[]}}
function syncOrderProductCells(){const rows=[...document.querySelectorAll('#ordersList .order-row:not(.head)')];const records=visibleRecords();if(!rows.length||!records.length)return;rows.forEach((row,index)=>{const r=records[index];if(!r)return;const cell=row.querySelector('.product-cell');if(!cell)return;const products=orderProducts(r);if(!products.length)return;const signature=products.map(p=>itemSku(p,r)+'|'+itemQty(p)).join(';;');if(row.dataset.abitProductSignature===signature)return;cell.innerHTML=`<div class="abit-product-list">${products.map(it=>{const image=itemImage(it),name=itemName(it),sku=itemSku(it,r),qty=itemQty(it);return `<div class="abit-product-item"><img class="product-img" src="${esc(image)}" onerror="this.onerror=null;this.style.visibility='hidden'"><div class="abit-product-info"><div class="name">${esc(name)}</div><div class="muted">SKU: ${esc(sku||'—')}</div><div class="muted">× ${fn(qty)}</div></div></div>`}).join('')}</div>`;row.dataset.abitProductSignature=signature})}
function patchRenderOrders(){if(typeof renderOrders!=='function'||renderOrders.__abitMulti)return;const original=renderOrders;function patched(...args){const result=original.apply(this,args);requestAnimationFrame(syncOrderProductCells);return result}patched.__abitMulti=true;globalThis.renderOrders=patched}

function parseApiDate(v){const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?new Date(+m[1],+m[2]-1,+m[3]):null}
function special(d){const day=d?.getDate?.(),month=d?.getMonth?.()+1;return day===1||day===10||day===15||day===20||day===25||day===month}
function patchPayloadLimit(){if(typeof payload!=='function'||payload.__abitLimit)return;const original=payload;function patched(start,end,statuses,page,limit){let a=parseApiDate(start),b=parseApiDate(end),hit=false;if(a&&b){for(let d=new Date(a),i=0;i<400&&d<=b;i++,d.setDate(d.getDate()+1))if(special(d)){hit=true;break}}return original.call(this,start,end,statuses,page,hit?Math.max(Number(limit)||100,400):(Number(limit)||100))}patched.__abitLimit=true;globalThis.payload=patched}

function css(){if($('#skuFilterStyle'))return;const s=document.createElement('style');s.id='skuFilterStyle';s.textContent=`.sku-filter-btn{height:42px;width:42px;min-width:42px;padding:0;border:1px solid #2b4567;border-radius:10px;background:#13243a;color:#dceaff;font-size:19px;font-weight:800;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;flex:0 0 42px}.sku-filter-btn:hover{background:#1267d9;color:#fff}.sku-modal-backdrop{position:fixed;inset:0;z-index:1000;background:rgba(3,9,18,.72);display:none;align-items:center;justify-content:center;padding:20px}.sku-modal-backdrop.open{display:flex}.sku-modal{width:min(1080px,100%);max-height:84vh;background:#0f1a2b;border:1px solid #29415f;border-radius:16px;overflow:hidden}.sku-modal-head{display:flex;justify-content:space-between;align-items:center;padding:17px 20px;border-bottom:1px solid #20334d}.sku-modal-body{overflow:auto;max-height:65vh}.sku-table{width:100%;border-collapse:collapse}.sku-table th,.sku-table td{padding:10px 14px;border-bottom:1px solid #1a2c43;text-align:left}.sku-table th:nth-child(n+3),.sku-table td:nth-child(n+3){text-align:right}.sku-product{display:flex;align-items:center;gap:11px}.sku-product-img{width:52px;height:52px;border-radius:8px;object-fit:cover}@media(max-width:760px){.orders-head{display:flex!important;align-items:center!important;gap:8px!important}.orders-head .search{flex:1;min-width:0}.sku-table thead{display:none}.sku-table,.sku-table tbody,.sku-table tr,.sku-table td{display:block;width:100%}.sku-table tr{padding:12px}.sku-table td{border:0;padding:4px 0}.sku-table td:nth-child(3)::before{content:'Số lượng SKU: ';color:#7187a3}.sku-table td:nth-child(4)::before{content:'Số lượng đơn: ';color:#7187a3}.abit-product-item{align-items:flex-start}}`;document.head.appendChild(s)}
function summary(){const records=visibleRecords(),m=new Map();for(const r of records){const oid=String(r.eoi_order_id??r.order_id??r.orderId??r.subject??'').trim();for(const p of orderProducts(r)){const sku=itemSku(p,r);if(!sku)continue;const key=skuKey(sku);let x=m.get(key);if(!x)x={sku,name:itemName(p),image:itemImage(p),qty:0,orders:new Set()};x.qty+=itemQty(p);if(oid)x.orders.add(oid);m.set(key,x)}}return[...m.values()].sort((a,b)=>b.qty-a.qty||b.orders.size-a.orders.size)}
function renderSku(){const body=$('skuModalBody'),sub=$('skuModalSub'),foot=$('skuModalFoot');if(!body)return;const rows=summary();if(sub)sub.textContent=`Từ ${fn(visibleRecords().length)} đơn đang hiển thị`;if(foot)foot.textContent=`${fn(rows.length)} SKU`;body.innerHTML=rows.length?`<table class="sku-table"><thead><tr><th>Ảnh, Tên SP</th><th>Mã SKU</th><th>Số lượng SKU</th><th>Số lượng đơn</th></tr></thead><tbody>${rows.map(x=>`<tr><td><div class="sku-product">${x.image?`<img class="sku-product-img" src="${esc(x.image)}">`:''}<div>${esc(x.name)}</div></div></td><td>${esc(x.sku)}</td><td>${fn(x.qty)}</td><td>${fn(x.orders.size)}</td></tr>`).join('')}</tbody></table>`:'<div style="padding:48px;text-align:center;color:#8fa3c0">Không tìm thấy SKU trong danh sách đơn hàng hiện tại.</div>'}
function install(){const h=document.querySelector('.orders-head');if(h&&!$('#skuFilterBtn')){const b=document.createElement('button');b.id='skuFilterBtn';b.className='sku-filter-btn';b.type='button';b.title='Lọc SKU';b.textContent='▦';b.onclick=()=>{$('skuModal')?.classList.add('open');renderSku()};h.appendChild(b)}if(!$('#skuModal')){const w=document.createElement('div');w.id='skuModal';w.className='sku-modal-backdrop';w.innerHTML='<div class="sku-modal"><div class="sku-modal-head"><div><b>Lọc SKU</b><div id="skuModalSub" style="font-size:11px;color:#8fa3c0;margin-top:4px"></div></div><button id="skuClose" style="font-size:22px;background:transparent;border:0;color:#fff">×</button></div><div class="sku-modal-body" id="skuModalBody"></div><div id="skuModalFoot" style="padding:10px 16px;color:#7489a4;font-size:11px"></div></div>';document.body.appendChild(w);$('#skuClose').onclick=()=>w.classList.remove('open');w.onclick=e=>{if(e.target===w)w.classList.remove('open')}}
const loginLogo=document.querySelector('.login-card .logo');if(loginLogo&&!loginLogo.querySelector('img'))loginLogo.innerHTML=`<img src="${BRAND}" alt="Abit Store Manager">`;const brand=document.querySelector('.sidebar .brand');if(brand&&brand.dataset.brandReady!=='1'){brand.innerHTML=`<img src="${BRAND}" alt=""> <span>Abit Store Manager</span>`;brand.dataset.brandReady='1'}}
css();patchReport();patchRenderOrders();patchPayloadLimit();const ob=new MutationObserver(()=>{install();patchReport();patchRenderOrders();patchPayloadLimit();syncOrderProductCells()});ob.observe(document.documentElement,{childList:true,subtree:true});install();setInterval(()=>{patchReport();patchRenderOrders();patchPayloadLimit();syncOrderProductCells()},250);
})();